version: "3"

services:

  marketing:
    image: node:12
    container_name: marketing
    restart: on-failure
    volumes:
      - .:/usr/src/app
    ports:
      - '3000:3000'
    # environment:
      # API_PORT: 9020
    working_dir: /usr/src/app
    command: bash -c "while true; do sleep 1; done"